// <auto-generated />
using BooksShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BooksShop.Migrations
{
    [DbContext(typeof(BooksShopDbContext))]
    [Migration("20240331163039_fillBooks")]
    partial class fillBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BooksShop.Data.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Дерманський Сашко"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ролінґ Дж.К."
                        },
                        new
                        {
                            Id = 3,
                            Name = "Олефір Юлія"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Костенко Ліна"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Федієнко Василь"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Протеро Стівен"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Кентербері Дейв"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Дубчак Ольга"
                        });
                });

            modelBuilder.Entity("BooksShop.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Discount = 5,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/m/a/malim-ditjam-pro-vse-na-sviti-enciklopedija-v-kazkah_2.webp",
                            InStock = true,
                            Name = "Малим дітям про все на світі",
                            Price = 470m,
                            Quantity = 10,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 1,
                            Discount = 10,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/l/i/lizla-zhaba-po-drabini.webp",
                            InStock = true,
                            Name = "Лізла жаба по драбині",
                            Price = 320m,
                            Quantity = 5,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CategoryId = 1,
                            Discount = 0,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/285x395/g/a/garri-potter-i-filosovs-kij-kamin-chastina-1_3.webp",
                            InStock = true,
                            Name = "Гаррі Поттер і філософський камінь (Частина 1)",
                            Price = 320m,
                            Quantity = 12,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CategoryId = 1,
                            Discount = 5,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/g/a/garri-potter-i-taemna-kimnata-chastina-2_3.webp",
                            InStock = true,
                            Name = "Гаррі Поттер і таємна кімната (Частина 2)",
                            Price = 320m,
                            Quantity = 8,
                            Year = 2021
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CategoryId = 1,
                            Discount = 15,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/k/a/kazkovij-lis-prigodi-enotiv-beshketnikiv.webp",
                            InStock = false,
                            Name = "Казковий ліс",
                            Price = 400m,
                            Quantity = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            CategoryId = 2,
                            Discount = 0,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/3/0/300-poezij_3.webp",
                            InStock = true,
                            Name = "Триста поезій",
                            Price = 350m,
                            Quantity = 20,
                            Year = 2012
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            CategoryId = 2,
                            Discount = 0,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/m/a/marusja-churaj_7.webp",
                            InStock = true,
                            Name = "Маруся Чурай",
                            Price = 350m,
                            Quantity = 10,
                            Year = 2018
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 5,
                            CategoryId = 3,
                            Discount = 0,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/m/i/mi-gotuemos-do-shkoli-krok-do-shkoli_2.webp",
                            InStock = true,
                            Name = "Ми готуємось до школи",
                            Price = 175m,
                            Quantity = 11,
                            Year = 2024
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            CategoryId = 3,
                            Discount = 5,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/b/u/bukvar-dlja-doshkil-njat-chitajlik-a4-korablik_4.webp",
                            InStock = true,
                            Name = "Буквар для дошкільнят",
                            Price = 140m,
                            Quantity = 8,
                            Year = 2015
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            CategoryId = 4,
                            Discount = 15,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/285x395/v/i/visim-religij-scho-panujut-u-sviti-chomu-ihni-vidminnosti-majut-znachennja_8.webp",
                            InStock = true,
                            Name = "Вісім релігій, що панують у світі",
                            Price = 250m,
                            Quantity = 1,
                            Year = 2022
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 7,
                            CategoryId = 5,
                            Discount = 0,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/b/u/bushkraft-najvazhlivishi-navichki-dlja-vizhivannja-v-dikij-prirodi_1.webp",
                            InStock = false,
                            Name = "Бушкрафт",
                            Price = 290m,
                            Quantity = 0,
                            Year = 2023
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 8,
                            CategoryId = 5,
                            Discount = 0,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/285x395/b/a/bachiti-ukrains-koju_2.webp",
                            InStock = true,
                            Name = "Бачити українською",
                            Price = 350m,
                            Quantity = 16,
                            Year = 2024
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 8,
                            CategoryId = 5,
                            Discount = 0,
                            ImageUrl = "https://bookopt.com.ua/media/catalog/product/cache/image/850x/c/h/chuti-ukrains-koju-u-sviti-zvuki-u-i-bukv_2.webp",
                            InStock = true,
                            Name = "Чути українською",
                            Price = 290m,
                            Quantity = 13,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("BooksShop.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Дитяча"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Художня"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Навчальна"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Культура"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Дозвілля"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Мова"
                        });
                });

            modelBuilder.Entity("BooksShop.Data.Entities.Book", b =>
                {
                    b.HasOne("BooksShop.Data.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BooksShop.Data.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BooksShop.Data.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BooksShop.Data.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
